### ISSUE TITLE
Addon Readme

### ISSUE THREAD

**Issue by Autoradiowecker** [Lamarqe/fritzmesh#8]
Hi Lamarqe,

could you please update your installation Readme.md .

It says: the addon store is on:  Configuration -> Addons, Backups & Supervisor -> Add-on Store

On Home Assistent 12 it is Settings -> Addons -> maybe Add-on Store

Maybe include a sentence that you need to refresh the page. At least this was the case for me. 

Keep up the good work.
Take care,
Clemens

**Comment by Lamarqe** [comment]
Thank you for making me aware.

Fixed with https://github.com/Lamarqe/fritzmesh/commit/eff794c743cfdf7696ecd85387d144daed33bed3
